apps/core/urls.py
from django.urls import path, include, re_path

from apps.core.views import *

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name = 'index'),
    path('qui-sommes-nous', AboutUsView.as_view(), name = 'about-us'),
    path('faite-vous-connaitre', KYCView.as_view(), name = 'kyc'),
    path('faite-vous-connaitre/denomination', KYCViewDenomination.as_view(), name = 'kyc-denomination'),
    path('faite-vous-connaitre/lieu-de-culte', KYCViewPlace.as_view(), name = 'kyc-place'),
    path('faite-vous-connaitre/service', KYCViewService.as_view(), name = 'kyc-service'),
]

# AJAX PATTERNS
urlpatterns += [
    re_path(r'^ajax/location-search$', location_search, name = 'location-search'),
    re_path(r'^ajax/place-search$', place_search, name = 'place-search'),
    re_path(r'^ajax/get-location$', get_location, name = 'get-location'),
    re_path(r'^ajax/get-next-celebration$', get_next_celebration, name = 'get-next'),
    re_path(r'^ajax/add-activity-request$', ActivityRequestView.as_view(), name = 'add-activity-request'),
    re_path(r'^ajax/add-contact-request$', ContactRequestView.as_view(), name = 'add-contact-request'),
    re_path(r'^ajax/add-receive-request$', ReceiveRequestCreateView.as_view(), name = 'add-receive-request'),
    re_path(r'^ajax/get-retirement-travel$', get_retirement_travel, name = 'get-retirement-travel'),
]

# FRAMES
urlpatterns += [
    re_path(r'^frame/(?P<request_type>\w+)$', open_frame, name = 'open-frame'),
]

# MAIN ROUTES
urlpatterns += [
    path('<slug:group>', DenominationListView.as_view(), name = 'group'),
    path('<slug:group>/necrologie', NecrologyListView.as_view(), name = 'necrology-list-group'),
    # path('<slug:group>/articles', ArticleListGroupView.as_view(), name = 'articles_group'),
    # path('<slug:group>/announces', views.AnnounceListGroupView.as_view(), name = 'announces_group'),
    # path('<slug:group>/calendar-view', CalendarPartialView.as_view(), name = 'calendar_group_view'),
    path('<slug:group>/', include([
        path('<slug:denomination>', DenominationHomeView.as_view(), name = 'denomination'),
        # NEWS
        path('<slug:denomination>/articles', ArticleListView.as_view(), name = 'article-list'),
        path('<slug:denomination>/article/<slug:slug>', ArticleDetailView.as_view(), name = 'article'),
        path('<slug:denomination>/annonces', AnnounceListView.as_view(), name = 'announce-list'),
        path('<slug:denomination>/annonce/<slug:slug>', AnnounceDetailView.as_view(), name = 'announce'),

        # FAITH
        path('<slug:denomination>/foi', DenominationFaithListView.as_view(), name = 'faith-list'),
        path('<slug:denomination>/foi/<slug:slug>', DenominationFaithView.as_view(), name = 'faith'),

        # DIRECTORY
        path('<slug:denomination>/je-recherche', DirectoryLookupView.as_view(), name = 'directory-lookup'),
        path('<slug:denomination>/directory-search-full', DirectorySearchFullView.as_view(), name = 'directory-search-full'),
        path('<slug:denomination>/annuaire/search', DirectoryWishSearchView.as_view(), name = 'annuaire-search'),
        path('<slug:denomination>/annuaire/<slug:slug>', PlaceView.as_view(), name = 'place'),
        # path('<slug:denomination>/annuaire/<slug:slug>/annonces', PlaceView.as_view(), name = 'place-announces'),
        path('<slug:denomination>/annuaire/<slug:place>/annonces/<slug:announce>', PlaceAnnounceDetailView.as_view(), name = 'place-announce'),
        path('<slug:denomination>/annuaire/<slug:place>/communauté/<slug:community>', PlaceCommunityDetailView.as_view(), name = 'place-community'),
        path('<slug:denomination>/annuaire/<slug:place>/remonter-une-erreur', ContactRequestView.as_view(), name = 'error-report'),
        # FORM ACTIVITY DIRECT LINK
        path('<slug:denomination>/annuaire/<slug:slug>/priere/<int:pk>', PlaceView.as_view(), name = 'prayer'),
        path('<slug:denomination>/evenements/<slug:slug>', EventView.as_view(), name = 'event'),
        path('<slug:denomination>/services/<slug:slug>', ServiceView.as_view(), name = 'service'),

        # TOOLS
        path('<slug:denomination>/faire-une-demande', ActivityRequestView.as_view(), name = 'activity-request'),
        path('<slug:denomination>/faire-une-demande/p/<slug:place>', ActivityRequestView.as_view(),
             name = 'activity-request-from-place'),
        path('<slug:denomination>/faire-une-demande/n/<slug:necrology>', ActivityRequestView.as_view(),
             name = 'activity-request-from-necrology'),
        path('<slug:denomination>/contacter', ContactRequestView.as_view(), name = 'contact-request'),

        path('<slug:denomination>/demandes', ReceiveRequestListView.as_view(), name = 'receive-list'),
        path('<slug:denomination>/demandes/<int:pk>', ReceiveRequestDetailView.as_view(), name = 'receive'),
        path('<slug:denomination>/solliciter-une-aide', ReceiveRequestCreateView.as_view(), name = 'receive-create'),
        path('<slug:denomination>/demandes/<int:pk>/donner', ReceiveRequestDonationView.as_view(), name = 'receive-donate'),

        # RETIREMENT
        path('<slug:denomination>/pelerinages-retraites', RetirementPlaceListView.as_view(), name = 'retirement-place-list'),
        path('<slug:denomination>/retirement-search', RetirementSearchView.as_view(), name = 'retirement-search'),
        path('<slug:denomination>/pelerinages-retraites/recherche', RetirementTravelSearchView.as_view(), name = 'retirement-travel-search'),
        path('<slug:denomination>/pelerinages-retraites/<slug:slug>', RetirementPlaceDetailView.as_view(), name = 'retirement-place'),

        # NECROLOGY
        path('<slug:denomination>/necrologie', NecrologyListView.as_view(), name = 'necrology-list'),
        path('<slug:denomination>/necrologie/search', NecrologyListView.as_view(), name = 'necrology-search'),
        path('<slug:denomination>/necrologie/<slug:slug>', NecrologyDetailView.as_view(), name = 'necrology'),

        # TESTIMONY
        path('<slug:denomination>/temoignages', TestimonyListView.as_view(), name = 'testimony-list'),
        path('<slug:denomination>/testimony/<slug:slug>', TestimonyDetailView.as_view(), name = 'testimony'),

        # MEDIA
        path('<slug:denomination>/ebook', EbookListView.as_view(), name = 'ebook-ist'),
        # path('<slug:denomination>/ebook/<slug:slug>', EbookDetailView.as_view(), name = 'ebook'),
        path('<slug:denomination>/mediatheque', GalleryListView.as_view(), name = 'media-list'),
        path('<slug:denomination>/mediatheque/<slug:type>', GalleryView.as_view(), name = 'media-type'),
        path('<slug:denomination>/mediatheque/<slug:type>/<int:pk>', GalleryDetailView.as_view(), name = 'media'),
    ])),
]

prions/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.utils.translation import ugettext_lazy
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

from prions.settings import cfg

admin.site.site_title = ugettext_lazy('{}'.format(cfg.get('PROJECT', 'APP_DESCRIPTION')))
admin.site.site_header = ugettext_lazy('{}'.format(cfg.get('PROJECT', 'APP_DESCRIPTION')))

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url = '/static/core/icons/favicon.ico')),
    # path('api/', include('backend.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace = 'core')),
    path('administrator/', include('apps.administrator.urls', namespace = 'administrator')),
    # re_path('api/(?P<version>(v1|v2))/', include('apps.api.urls', namespace = 'api')),
    # path('api-auth/', include('rest_framework.urls', namespace = 'rest_framework')),
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# Other plugins urls
urlpatterns += [
    re_path(r'^captcha/', include('captcha.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

# If you already have a js_info_dict dictionary, just add
# 'recurrence' to the existing 'packages' tuple.
"""js_info_dict = {
    'packages': ('recurrence',),
}"""

# jsi18n can be anything you like here
"""urlpatterns += [
    re_path(r'^jsi18n/$', JavaScriptCatalog.as_view(), js_info_dict),
]"""

urlpatterns += [path('jsi18n.js', JavaScriptCatalog.as_view(packages = ['recurrence']), name = 'jsi18n'), ]

# For Ads
# urlpatterns += re_path(r'^ads/', include('ads.urls')),

if settings.DEBUG is True:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

apps/core/views/ajax.py
import json
from datetime import datetime
from itertools import chain

from django.contrib.sites.models import Site
from django.core import signing
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt

from apps.location.models import City, Town, Borough
from apps.religion.models import Place, Group, Denomination, PlaceActivity
from apps.retirement.models import RetirementTravelInstance
from lib.config import django_logger
from lib.middleware import api_call, str_to_json, get_geo_loc, get_occurrences, nearest_date, get_class_instance, get_activity, JSONEncoder
from lib.resources import confs


def location_search(request):
    get_data = request.GET
    location = get_data.get('location', None)

    status = False
    results = []

    cities_list = City.objects.filter(name__icontains = location).values()
    city = [dict(x, type = 'city') for x in cities_list]

    towns_list = Town.objects.filter(name__icontains = location).values()
    town = [dict(x, type = 'town') for x in towns_list]

    boroughs_list = Borough.objects.filter(name__icontains = location).values()
    borough = [dict(x, type = 'borough') for x in boroughs_list]

    values = sorted(chain(city, town, borough), key = lambda instance: instance['name'])

    if values:
        status = True
        results = values

    data = {
        'status': status,
        'results': results,
    }

    return JsonResponse(data, safe = False)


def place_search(request):
    get_data = request.GET
    place_name = get_data.get('place_name', '')
    place_type = get_data.get('place_type', '')
    denomination = get_data.get('denomination', '')

    status = False
    results = []

    place = Place.objects.posted_by_denomination(denomination)
    if len(place_type) > 0:
        place = place.filter(place_type = place_type)
    place = place.filter(name__icontains = place_name)

    if place:
        status = True
        results = list(place.values())

    data = {
        'status': status,
        'results': results,
    }

    return JsonResponse(data, safe = False)


@csrf_exempt
def get_location(request):
    latitude = request.POST.get('latitude', None)
    longitude = request.POST.get('longitude', None)

    if latitude and longitude:
        geo_api = confs.get('api')['GEO_API']

        url = geo_api['url'].replace('{latitude}', latitude).replace('{longitude}', longitude)
        place = api_call(url = url, method = geo_api['method'], timeout = 5)

        if not hasattr(place, 'status_code'):
            out_msg = place["message"]
            django_logger.error("GEO API NOT REACHABLE !!! => {}".format(out_msg))

            return JsonResponse(None, safe = False)
        else:
            r = place.text
            return JsonResponse(json.loads(r))


def get_retirement_travel(request):
    get_data = request.GET
    instance_id = get_data.get('instance', '')
    group_id = get_data.get('group', '')
    denomination_id = get_data.get('denomination', '')

    group = get_class_instance(Group, pk = group_id)
    denomination = get_class_instance(Denomination, pk = denomination_id)

    status = False

    instance = get_class_instance(RetirementTravelInstance, pk = instance_id)
    template = ''

    if instance:
        status = True
        # template = TemplateResponse(request, 'core/denomination/partials/modals/retirement_travel_instance.html', context = instance)
        context = {
            'request': request,
            'group': group,
            'denomination': denomination,
            'instance': instance
        }
        template = render_to_string('core/denomination/partials/modals/retirement_travel_instance.html', context)

    data = {
        'status': status,
        'travel_title': '{} ({})'.format(instance.retirement_travel.title, instance.departure_date.year),
        'template': template,
    }

    return JsonResponse(data, safe = False)


@csrf_exempt
def get_next_celebration(request):
    post = request.POST
    group = post.get('group', None)
    denomination = post.get('denomination', None)
    geo_loc = str_to_json(post.get('address', ""))

    from apps.religion.models import PlaceActivity
    place_activities = PlaceActivity.objects.filter(place__denomination = denomination, activity__activity_type__codename = "messe")

    search_result = get_geo_loc(PlaceActivity, geo_loc, place_activities, by = "address", place = True)

    occ = [get_occurrences(x.id, 'next') for x in search_result if get_occurrences(x.id, 'next') and x.recurrences is not None]

    next_occ = nearest_date(occ, datetime.today().date())
    template = ''

    if next_occ is None:
        status = False
    else:
        status = True
        domain = Site.objects.get_current().domain
        pa = next_occ.get('place_activity', {})
        date = next_occ.get('date', None)
        pa_params = {'frame': True, 'type': 'activity', 'id': pa.activity.pk, 'date': date.strftime('%d-%m-%Y')}
        encoded_params = signing.dumps(pa_params)
        # next_occ['url'] = url_with_querystring(domain, encoded_params)
        next_occ['url'] = "{}?r={}".format(domain, encoded_params)
        next_occ['request'] = request
        template = render_to_string('core/denomination/partials/modals/next_celebration.html', next_occ)

    data = {
        'status': status,
        'template': template,
    }

    return JsonResponse(data)


def open_frame(request, params):
    if bool(params) is True:
        request_type = params.get('type')
        pa_id = params.get('id')
        date = params.get('date')
        if request_type == 'activity':
            place_activity = get_class_instance(PlaceActivity, pa_id)
            activity_date = date
            occ = get_activity(place_activity, activity_date)
            next_occ = nearest_date(occ, datetime.today().date())
            next_occ['request'] = request
            next_occ['frame'] = True

            template = ''

            if next_occ is None:
                status = False
            else:
                status = True
                template = render_to_string('core/denomination/partials/modals/next_celebration.html', next_occ)

            data = {
                'status': status,
                'template': template,
            }

            return json.dumps(data)

        print("get_data => {}".format(get_data))
        instance_id = get_data.get('instance', '')
        group_id = get_data.get('group', '')
        denomination_id = get_data.get('denomination', '')
        frame = get_data.get('open_frame', '')
        print("frame => {}".format(frame))
        return

        group = get_class_instance(Group, pk = group_id)
        denomination = get_class_instance(Denomination, pk = denomination_id)

        status = False

        instance = get_class_instance(RetirementTravelInstance, pk = instance_id)
        template = ''

        if instance:
            status = True
            # template = TemplateResponse(request, 'core/denomination/partials/modals/retirement_travel_instance.html', context = instance)
            context = {
                'request': request,
                'group': group,
                'denomination': denomination,
                'instance': instance
            }
            template = render_to_string('core/denomination/partials/modals/retirement_travel_instance.html', context)

        data = {
            'status': status,
            'travel_title': '{} ({})'.format(instance.retirement_travel.title, instance.departure_date.year),
            'template': template,
        }

        return JsonResponse(data, safe = False)

apps/core/templates/core/denomination/partials/widgets/calendar.html
<div class="col-lg-12 col-sm-6 col-md-6 bottommargin-sm" id="custom_calendar">
    <div class="fancy-title title-dotted-border title-center">
        <h4 class="color">Agenda {% if place %}{{ place.name }}{% endif %} </h4>
    </div>
    <div id="calendar" data-events="{{ calendar_events }}"></div>
</div>

apps/core/templates/core/denomination/partials/widgets/i_wish.html
{% load static %}
<div class="fancy-title title-bottom-border title-center">
    <h5>
        Je cherche <span class="rotate color">{% for type in rotate_list %}
        {{ type }}
        {% if not forloop.last %},{% endif %}
    {% endfor %}</span>
    </h5>
</div>
<div>
    {% if page_name == 'home_denomination' %}
        <div class="d-none d-sm-none d-md-none d-lg-block">
            <div class="fancy-title title-dotted-border title-center">
                <h6>Rechercher sur la carte</h6>
            </div>
            <a href="#">
                <img src="{% static 'core/images/ivory_coast_map.svg' %}" alt="" id="home-annuaire-svg">
            </a>
        </div>
    {% endif %}
    <div class="fancy-title title-dotted-border title-center">
        <h6>Utiliser des crit&egrave;res de recherche</h6>
    </div>
    <div>
        <form action="{% url 'core:annuaire-search' group.slug denomination.slug %}" method="post" id="i-wish" data-search-url="annuaire">
            {% csrf_token %}
            <div class="">
                <input type="radio" name="search_type" id="worship-place" value="worship-place">
                <label for="worship-place">&nbsp;{{ denomination.denomination_details.place_type }}</label>
            </div>
            <div class="">
                <input type="radio" name="search_type" id="worship-activity" value="worship-activity">
                <label for="worship-activity">&nbsp;Horaires de {{ denomination.denomination_details.celebration }}</label>
            </div>
            <div class="">
                <input type="radio" name="search_type" id="worship-event" value="worship-event">
                <label for="worship-event">&nbsp;&Eacute;v&eacute;nements</label>
            </div>
            <div class="">
                <input type="radio" name="search_type" id="worship-service" value="worship-service">
                <label for="worship-service">&nbsp;Services & associations</label>
            </div>

            <div class="worship-place">
                <div class="form-group">
                    <select name="place_type" id="place-type" class="form-control">
                        <option value="">Tout</option>
                        {% for place_type in place_types %}
                            <option value="{{ place_type.id }}">{{ place_type.name }}</option>
                        {% endfor %}
                    </select>
                    <small class="form-text">S&eacute;lectionnez un type de {{ denomination.denomination_details.place_type }}</small>
                </div>
                <div class="form-group">
                    <input type="text" name="place" id="place" class="form-control place"
                           placeholder="Entrez le nom d'un {{ denomination.denomination_details.place_type }}" autocomplete="off">
                    <ul class="widget-links clearfix place-results live-results"></ul>
                    <small class="form-text">Entrez le nom d'un {{ denomination.denomination_details.place_type }}</small>
                </div>
            </div>

            <div class="worship-activity">
                <div class="form-group">
                    <input type="text" name="place" id="activity-place" class="form-control place"
                           placeholder="Entrez le nom d'un {{ denomination.denomination_details.place_type }}" autocomplete="off">
                    <ul class="widget-links clearfix place-results live-results"></ul>
                    <small class="form-text">Entrez le nom d'un {{ denomination.denomination_details.place_type }}</small>
                </div>
                <div class="form-group">
                    <input type="text"
                           name="activity_date"
                           id="activity_date"
                           class="form-control tleft select-date"
                           placeholder="jj/mm/aaaa"
                           autocomplete="off">
                    <small class="form-text">S&eacute;lectionnez une date</small>
                </div>
            </div>

            <div class="worship-event">
                <div class="form-group">
                    <select name="event_type" id="event-type" class="form-control">
                        <option value="">Tout</option>
                        {% for event_type in event_types %}
                            <option value="{{ event_type.id }}">{{ event_type.name }}</option>
                        {% endfor %}
                    </select>
                    <small class="form-text">S&eacute;lectionnez un type</small>
                </div>
                <div class="form-group">
                    <input type="text"
                           name="event_date"
                           id="event-date"
                           class="form-control tleft select-date"
                           placeholder="jj/mm/aaaa"
                           autocomplete="off">
                    <small class="form-text">S&eacute;lectionnez une date</small>
                </div>
            </div>

            <div class="worship-service">
                <div class="form-group">
                    <select name="service_type" id="service-type" class="form-control">
                        <option value="">Tout</option>
                        {% for service_type in service_types %}
                            <option value="{{ service_type.id }}">{{ service_type.name }}</option>
                        {% endfor %}
                    </select>
                    <small class="form-text">S&eacute;lectionnez un type</small>
                </div>
            </div>

            <div id="location-search-block" class="form-group">
                <div class="input-group">
                    <input type="text"
                           id="location-search"
                           name="location_search"
                           class="form-control location-search"
                           placeholder="Localisation"
                           autocomplete="off">
                    <div class="input-group-append">
                        <button class="btn button-color get-location"
                                type="button"
                                data-toggle="tooltip"
                                title="Me Localiser">
                            <i class="fa fa-location-arrow"></i>
                        </button>
                    </div>
                </div>
                <ul class="widget-links clearfix location-results live-results"></ul>
                <small class="form-text">Entrez le nom d'un quartier, d'une ville</small>
                <input type="hidden" name="geo_loc">
            </div>

            <input type="hidden" name="search_elements">
            <input type="hidden" name="denomination">

            <div id="search-button-block" class="form-group">
                <button type="submit" class="button button-3d button-color btn-block noleftmargin norightmargin">
                    <span>Rechercher</span>
                </button>
            </div>
        </form>
    </div>
</div>

apps/core/templates/core/denomination/partials/widgets/islam_prayer_time.html
<div class="clearfix col-lg-12 col-sm-12 col-md-12 mb-lg-5">
    <div class="row">
        {% comment %}<iframe class="col-lg-12 col-sm-12 col-md-12"
                style="height: 358px; border: 1px solid #ddd !important;"
                frameBorder="0" scrolling="no"
                src="https://www.islamicfinder.org/prayer-widget/?language=fr"></iframe>{% endcomment %}
        <iframe id="iframe"
                title="prayerWidget"
                class="col-lg-12 col-sm-12 col-md-12"
                style="height: 358px; border: 1px solid #ddd !important;"
                scrolling="no"
                src="https://www.islamicfinder.org/prayer-widget/2293538/shafi/1/0/18.0/17.0?language=fr"></iframe>
    </div>
</div>

apps/core/templates/core/denomination/partials/widgets/necrology.html
{% load static thumbnail %}
<div class="col-lg-12 col-sm-6 col-md-6 necrology bottommargin-sm">
    <div class="fancy-title title-dotted-border title-center">
        <a href="{% url 'core:necrology-list' group.slug denomination.slug %}"><h4 class="color">N&eacute;crologie</h4></a>
    </div>

    <div class="bxslider">
        {% for necrology in necrology_list %}
            <div class="necroloy-link"
                 data-url="{% url 'core:necrology' group.slug denomination.slug necrology.slug %}">
                <a href="{% url 'core:necrology' group.slug denomination.slug necrology.slug %}">
                    {% thumbnail necrology.image "350x288" crop="100% top" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}"
                             height="{{ im.height }}" alt="{{ necrology.title }}" title="{{ necrology.title }}">
                    {% empty %}
                        <img src="https://placehold.jp/cccccc/ffffff/350x288.png?text=Aucune%20Image%20trouv%C3%A9e"
                             alt="{{ necrology.title }}" title="{{ necrology.title }}">
                    {% endthumbnail %}
                </a>
                <div class="down-content caption text-center">
                    <a href="{% url 'core:necrology' group.slug denomination.slug necrology.slug %}">
                        <h4>{{ necrology.title }}</h4>
                    </a>
                    <p>{{ necrology.date }}</p>
                </div>
            </div>
        {% empty %}
            Aucun d&eacute;c&egrave;s enregistr&eacute; pour le moment
        {% endfor %}
    </div>
</div>