apps/administrator/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from apps.administrator.views import *

app_name = 'administrator'

urlpatterns = [
    # path('', IndexView.as_view(), name = 'index'),
    # path('login/', LoginView.as_view(), name = 'login'),
    path('login/', CustomLoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(next_page = '/administrator/login/?next=/administrator/'), name = 'logout'),

    # PLACE
    path('', PlaceView.as_view(), name = 'place'),

    # ACTIVITY
    path('activity/', ActivityCreateView.as_view(), name = 'activity'),
    path('activity/<int:pk>', ActivityUpdateView.as_view(), name = 'activity-update'),
    path('activity/schedule/<int:pk>/create', ActivityDetailsCreateView.as_view(), name = 'schedule-create'),
    path('activity/schedule/<int:pk>/update', ActivityDetailsUpdateView.as_view(), name = 'schedule-update'),

    # OFFICIANT
    path('officiants/', PlaceOfficiantListView.as_view(), name = 'officiant-list'),
    path('officiant/', PlaceOfficiantCreateView.as_view(), name = 'officiant-create'),
    path('officiants/<int:pk>', PlaceOfficiantUpdateView.as_view(), name = 'officiant-update'),

    # ORGANIZATION
    path('organizations/', OrganizationListView.as_view(), name = 'organization-list'),
    path('organization/', OrganizationCreateView.as_view(), name = 'organization-create'),
    path('organizations/<int:pk>', OrganizationUpdateView.as_view(), name = 'organization-update'),

    # PERSON
    path('persons/', ResponsibleListView.as_view(), name = 'person-list'),
    path('person/', ResponsibleCreateView.as_view(), name = 'person-create'),
    path('persons/<int:pk>', ResponsibleUpdateView.as_view(), name = 'person-update'),

    # CATEGORY
    path('categories/', CategoryListView.as_view(), name = 'category-list'),
    path('category/', CategoryCreateView.as_view(), name = 'category-create'),
    path('categories/<int:pk>', CategoryUpdateView.as_view(), name = 'category-update'),

    # TAG
    path('tags/', TagListView.as_view(), name = 'tag-list'),
    path('tag/', TagCreateView.as_view(), name = 'tag-create'),
    path('tags/<int:pk>', TagUpdateView.as_view(), name = 'tag-update'),

    # ANNOUNCE
    path('announces/', AnnounceListView.as_view(), name = 'announce-list'),
    path('announce/', AnnounceCreateView.as_view(), name = 'announce-create'),
    path('announces/<int:pk>', AnnounceUpdateView.as_view(), name = 'announce-update'),

    # LIFE
    path('communities/', CommunityListView.as_view(), name = 'community-list'),
    path('community/', CommunityCreateView.as_view(), name = 'community-create'),
    path('communities/<int:pk>', CommunityUpdateView.as_view(), name = 'community-update'),

    # EVENT
    path('events/', EventListView.as_view(), name = 'event-list'),
    path('event/', EventCreateView.as_view(), name = 'event-create'),
    path('events/<int:pk>', EventUpdateView.as_view(), name = 'event-update'),

    # SERVICE
    path('services/', ServiceListView.as_view(), name = 'service-list'),
    path('service/', ServiceCreateView.as_view(), name = 'service-create'),
    path('services/<int:pk>', ServiceUpdateView.as_view(), name = 'service-update'),
]

prions/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.utils.translation import ugettext_lazy
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

from prions.settings import cfg

admin.site.site_title = ugettext_lazy('{}'.format(cfg.get('PROJECT', 'APP_DESCRIPTION')))
admin.site.site_header = ugettext_lazy('{}'.format(cfg.get('PROJECT', 'APP_DESCRIPTION')))

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url = '/static/core/icons/favicon.ico')),
    # path('api/', include('backend.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace = 'core')),
    path('administrator/', include('apps.administrator.urls', namespace = 'administrator')),
    # re_path('api/(?P<version>(v1|v2))/', include('apps.api.urls', namespace = 'api')),
    # path('api-auth/', include('rest_framework.urls', namespace = 'rest_framework')),
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# Other plugins urls
urlpatterns += [
    re_path(r'^captcha/', include('captcha.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

# If you already have a js_info_dict dictionary, just add
# 'recurrence' to the existing 'packages' tuple.
"""js_info_dict = {
    'packages': ('recurrence',),
}"""

# jsi18n can be anything you like here
"""urlpatterns += [
    re_path(r'^jsi18n/$', JavaScriptCatalog.as_view(), js_info_dict),
]"""

urlpatterns += [path('jsi18n.js', JavaScriptCatalog.as_view(packages = ['recurrence']), name = 'jsi18n'), ]

# For Ads
# urlpatterns += re_path(r'^ads/', include('ads.urls')),

if settings.DEBUG is True:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

apps/administrator/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    place = models.ForeignKey('religion.Place', models.SET_NULL, blank = True, null = True, verbose_name = 'Lieu de prière')

    class Meta:
        verbose_name = 'Profil'
        verbose_name_plural = 'Profils'


@receiver(post_save, sender = User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user = instance)

apps/posts/models.py
from captcha.fields import CaptchaField
from ckeditor_uploader.fields import RichTextUploadingField
from dateutil.relativedelta import relativedelta
from django.db import models
from django.db.models import FileField
from django.urls import reverse
from django.utils import timezone
from django_countries.fields import CountryField
from sorl.thumbnail import ImageField

from apps.core.enums import STATUS_CHOICES, PUBLISHED, STATE_CHOICES, INACTIVATED, DEATH_LINK_CHOICES
from apps.managers import PostsQuerySet
from apps.managers.medias import MediaManager
from apps.religion.models import Religion
from lib.middleware import get_unique_slug, Monitor, Hider, upload_path, to_slug


class MediaType(Monitor):
    id = models.AutoField(primary_key = True)
    label = models.CharField(max_length = 45, blank = True, verbose_name = 'Libellé')
    codename = models.CharField(max_length = 90, blank = True, verbose_name = 'Type de média')

    class Meta:
        verbose_name = 'Type de média'
        verbose_name_plural = 'Types des médias'
        ordering = ['label']

    def __str__(self):
        return self.label

    def save(self, *args, **kwargs):
        codename = to_slug(self.label)
        if self.codename != codename:
            self.codename = codename
        super(MediaType, self).save(*args, **kwargs)


class MediaSourceType(Monitor):
    id = models.AutoField(primary_key = True)
    label = models.CharField(max_length = 45, blank = True, verbose_name = 'Libellé')
    codename = models.CharField(max_length = 90, blank = True, verbose_name = 'Type de média')

    class Meta:
        verbose_name = 'Source du média'
        verbose_name_plural = 'Sources des médias'
        ordering = ['label']

    def __str__(self):
        return self.label

    def save(self, *args, **kwargs):
        codename = to_slug(self.label)
        if self.codename != codename:
            self.codename = codename
        super(MediaSourceType, self).save(*args, **kwargs)


class Gallery(Monitor, Religion):
    id = models.BigAutoField(primary_key = True)
    type = models.ForeignKey(MediaType, models.PROTECT, verbose_name = 'Type de média')
    source_type = models.ForeignKey(MediaSourceType, models.PROTECT, blank = True, null = True, verbose_name = 'Source du média')
    name = models.CharField(max_length = 255, blank = True, verbose_name = 'Titre')
    slug = models.SlugField(unique = True)
    tags = models.ManyToManyField('posts.Tag', blank = True, verbose_name = 'Tags')
    description = models.TextField(default = '', blank = True, verbose_name = 'Description')
    file = models.FileField(upload_to = upload_path, blank = True, null = True, verbose_name = 'Fichier')
    link = models.URLField(blank = True, null = True, verbose_name = 'Lien')
    status = models.BooleanField(null = True, choices = STATUS_CHOICES, db_index = True, verbose_name = 'Statut')
    media_code = models.CharField(max_length = 60, blank = True, null = True, db_index = True, editable = False)
    place = Hider()
    objects = MediaManager()

    class Meta:
        verbose_name = 'Galérie'
        verbose_name_plural = 'Galéries'
        ordering = ['-created_at']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        slug = get_unique_slug(self, self.name)
        if self.slug != slug:
            self.slug = slug
        super(Gallery, self).save(*args, **kwargs)


class Category(Monitor, Religion):
    id = models.AutoField(primary_key = True)
    parent = models.ForeignKey('self', models.SET_NULL, blank = True, null = True, verbose_name = 'Catégorie Parent')
    name = models.CharField(max_length = 150, verbose_name = 'Nom')
    slug = models.SlugField(unique = True)
    status = models.BooleanField(null = True, default = PUBLISHED, db_index = True, verbose_name = 'Publié')
    place = Hider()

    class Meta:
        verbose_name = 'Catégorie'
        verbose_name_plural = 'Catégories'
        ordering = ['name']

    def __str__(self):
        return self.name


class Tag(Monitor):
    id = models.BigAutoField(primary_key = True)
    name = models.CharField(max_length = 60, unique = True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Post(Monitor, Religion):
    id = models.BigAutoField(primary_key = True)
    category = models.ForeignKey(Category, models.PROTECT, verbose_name = 'Catégorie')
    title = models.CharField(max_length = 170, db_index = True, verbose_name = 'Titre')
    slug = models.SlugField(unique = True)
    image = ImageField(upload_to = upload_path, blank = True, null = True, verbose_name = 'Image')
    file_url = models.URLField(blank = True, null = True, verbose_name = 'URL de l\'image')
    excerpt = models.CharField(max_length = 255, default = '', verbose_name = 'Résumé')
    tags = models.ManyToManyField(Tag, blank = True, verbose_name = 'Tags')
    flash = models.BooleanField(default = False, verbose_name = 'Flash ?')
    content = RichTextUploadingField(default = '', verbose_name = 'Contenu')
    source = models.CharField(max_length = 255, blank = True, verbose_name = 'Source de l\'article')
    # stick = models.BooleanField(default = False, verbose_name = '')
    status = models.BooleanField(null = True, choices = STATUS_CHOICES, db_index = True, verbose_name = 'Statut')
    published_on = models.DateTimeField(db_index = True, verbose_name = 'Publié le')
    end_publication = models.DateTimeField(db_index = True, blank = True, null = True, verbose_name = 'Fin de publication')
    absolute_url = models.CharField(max_length = 400, blank = True, editable = False)
    objects = PostsQuerySet().as_manager()

    class Meta:
        abstract = True
        ordering = ['-published_on']

    # def save(self, *args, **kwargs):
    #     slug = get_unique_slug(self, self.title)
    #     if self.slug != slug:
    #         self.slug = slug
    #     super(Post, self).save(*args, **kwargs)

    @property
    def is_actual(self):
        """
        Checks if an entry is within his publication period.
        """
        now = timezone.now()
        if self.published_on and now < self.published_on:
            return False

        if self.end_publication and now >= self.end_publication:
            return False
        return True

    @property
    def is_visible(self):
        """
        Checks if an entry is visible and published.
        """
        return self.is_actual and self.status == PUBLISHED

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url


class Article(Post):
    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:article',
                       kwargs = {
                           'group': self.group.slug,
                           'denomination': self.denomination.slug,
                           'slug': self.slug
                       })


class Announce(Post):
    # category = Hider()
    tags = Hider()
    flash = Hider()
    source = Hider()

    class Meta:
        verbose_name = 'Annonce'
        verbose_name_plural = 'Annonces'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:announce',
                       kwargs = {
                           'group': self.group.slug,
                           'denomination': self.denomination.slug,
                           'slug': self.slug
                       })


class Necrology(Post):
    date = models.DateField(db_index = True, verbose_name = 'Date du décès')
    content = RichTextUploadingField(default = '', blank = True, verbose_name = 'Annonce')
    ceremony = RichTextUploadingField(default = '', blank = True, verbose_name = 'Cérémonies')
    thanks = RichTextUploadingField(default = '', blank = True, verbose_name = 'Remerciements')
    in_memoriam = RichTextUploadingField(default = '', blank = True, verbose_name = 'In Memoriam')
    image = ImageField(upload_to = 'uploads/necrology/%Y/%m/%d/', blank = True, null = True)
    file = FileField(upload_to = 'uploads/necrology/%Y/%m/%d/', blank = True, null = True, verbose_name = 'Fichier, Flyer, ...')
    category = Hider()
    tags = Hider()
    group = Hider()
    denomination = Hider()
    place = Hider()
    flash = Hider()
    source = Hider()
    published_on = Hider()
    end_publication = Hider()

    class Meta:
        verbose_name = 'Nécrologie'
        verbose_name_plural = 'Nécrologie'
        ordering = ['-date']

    def __str__(self):
        return self.title

    @property
    def is_birthday(self):
        """
        Checks if it's the birthday of an entry.
        """
        now = timezone.now()
        if self.date.month == now.month and self.date.day == now.day:
            return True

    @property
    def has_thanks(self):
        """
        Checks if thanks entry is not empty
        """
        if len(self.thanks) > 0:
            return True
        return False

    @property
    def has_birth(self):
        """
        Checks if it's the birthday of an entry.
        """
        now = timezone.now()
        next_date = self.date + relativedelta(years = +1)
        if next_date <= now.date():
            return True
        return False


class NecrologyCondolences(Monitor):
    id = models.BigAutoField(primary_key = True)
    necrology = models.ForeignKey(Necrology, models.PROTECT, verbose_name = 'Décès')
    last_name = models.CharField(max_length = 160, verbose_name = 'Nom')
    first_name = models.CharField(max_length = 160, blank = True, verbose_name = 'Prénom(s)')
    email = models.EmailField(max_length = 160, verbose_name = 'Email',
                              help_text = 'Votre e-mail sera caché et servira à recevoir le message de remerciement de la famille')

apps/administrator/views/common.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView


class CustomLoginView(LoginView):
    template_name = 'administrator/auth/login.html'

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Login'
        context['page_name'] = 'index'

        return context


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'administrator/common/index.html'
    login_url = '/administrator/login/'

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Admin'
        context['page_name'] = 'index'

        return context

apps/administrator/templates/administrator/post/category_create.html
{% extends 'administrator/common/layout.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ page_title|default:"Bienvenue sur Prions.ci" }}{% endblock %}
{% block content_header %}
    <div class="content-header">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="page-title">{{ page_title }}</h3>
                <div class="d-inline-block align-items-center">
                    <nav>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
                            <li class="breadcrumb-item active" aria-current="page">{{ page_title }}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="box">
                    <div class="box-header">
                        <h4 class="box-title">{{ page_title }}</h4>
                    </div>
                    <div class="box-body">
                        {% crispy form %}
                    </div>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
    </section>
{% endblock %}

apps/administrator/templates/administrator/post/category_list.html
{% extends 'administrator/common/layout.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ page_title|default:"Bienvenue sur Prions.ci" }}{% endblock %}
{% block content_header %}
    <div class="content-header">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="page-title">{{ page_title }}</h3>
                <div class="d-inline-block align-items-center">
                    <nav>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
                            <li class="breadcrumb-item active" aria-current="page">{{ page_title }}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="box">
                    <div class="box-header">
                        <h4 class="box-title">{{ page_title }}</h4>
                    </div>
                    <div class="box-body">
                        <div class="table-responsive">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Titre</th>
                                    <th>Cat&eacute;gorie parent</th>
                                    <th>Statut</th>
                                    <th>Mis à jour le</th>
                                    <th>Par</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for placecategory in placecategory_list %}
                                    <tr>
                                        <td>{{ placecategory.pk }}</td>
                                        <td>{{ placecategory.name }}</td>
                                        <td>{{ placecategory.parent|default_if_none:"" }}</td>
                                        <td>{{ placecategory.get_status_display }}</td>
                                        <td>{{ placecategory.updated_at }}</td>
                                        <td>{{ placecategory.updated_by }}</td>
                                        <td>
                                            <div class="btn-group">
                                                <a href="{% url 'administrator:category-update' placecategory.pk %}" class="btn btn-info"><i
                                                        class="fa fa-edit"></i></a>
                                                <a href="" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>Titre</th>
                                    <th>Cat&eacute;gorie parent</th>
                                    <th>Statut</th>
                                    <th>Mis à jour le</th>
                                    <th>Par</th>
                                    <th>Actions</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
    </section>
{% endblock %}

apps/administrator/templates/administrator/post/category_update.html
{% extends 'administrator/common/layout.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ page_title|default:"Bienvenue sur Prions.ci" }}{% endblock %}
{% block content_header %}
    <div class="content-header">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="page-title">{{ page_title }}</h3>
                <div class="d-inline-block align-items-center">
                    <nav>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
                            <li class="breadcrumb-item active" aria-current="page">{{ page_title }}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="box">
                    <div class="box-header">
                        <h4 class="box-title">{{ page_title }}</h4>
                    </div>
                    <div class="box-body">
                        {% crispy form %}
                    </div>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
    </section>
{% endblock %}

apps/administrator/templates/administrator/post/tag_create.html
{% extends 'administrator/common/layout.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ page_title|default:"Bienvenue sur Prions.ci" }}{% endblock %}
{% block content_header %}
    <div class="content-header">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="page-title">{{ page_title }}</h3>
                <div class="d-inline-block align-items-center">
                    <nav>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
                            <li class="breadcrumb-item active" aria-current="page">{{ page_title }}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="box">
                    <div class="box-header">
                        <h4 class="box-title">{{ page_title }}</h4>
                    </div>
                    <div class="box-body">
                        {% crispy form %}
                    </div>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
    </section>
{% endblock %}

apps/administrator/templates/administrator/post/tag_list.html
{% extends 'administrator/common/layout.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ page_title|default:"Bienvenue sur Prions.ci" }}{% endblock %}
{% block content_header %}
    <div class="content-header">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="page-title">{{ page_title }}</h3>
                <div class="d-inline-block align-items-center">
                    <nav>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
                            <li class="breadcrumb-item active" aria-current="page">{{ page_title }}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="box">
                    <div class="box-header">
                        <h4 class="box-title">{{ page_title }}</h4>
                    </div>
                    <div class="box-body">
                        <div class="table-responsive">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Tag</th>
                                    <th>Mis à jour le</th>
                                    <th>Par</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for placetag in placetag_list %}
                                    <tr>
                                        <td>{{ placetag.pk }}</td>
                                        <td>{{ placetag.name }}</td>
                                        <td>{{ placetag.updated_at }}</td>
                                        <td>{{ placetag.updated_by }}</td>
                                        <td>
                                            <div class="btn-group">
                                                <a href="{% url 'administrator:tag-update' placetag.pk %}" class="btn btn-info"><i
                                                        class="fa fa-edit"></i></a>
                                                <a href="" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>Titre</th>
                                    <th>Mis à jour le</th>
                                    <th>Par</th>
                                    <th>Actions</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
    </section>
{% endblock %}

apps/administrator/templates/administrator/post/tag_update.html
{% extends 'administrator/common/layout.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ page_title|default:"Bienvenue sur Prions.ci" }}{% endblock %}
{% block content_header %}
    <div class="content-header">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="page-title">{{ page_title }}</h3>
                <div class="d-inline-block align-items-center">
                    <nav>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
                            <li class="breadcrumb-item active" aria-current="page">{{ page_title }}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="box">
                    <div class="box-header">
                        <h4 class="box-title">{{ page_title }}</h4>
                    </div>
                    <div class="box-body">
                        {% crispy form %}
                    </div>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
    </section>
{% endblock %}