apps/core/urls.py
from django.urls import path, include, re_path

from apps.core.views import *

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name = 'index'),
    path('qui-sommes-nous', AboutUsView.as_view(), name = 'about-us'),
    path('faite-vous-connaitre', KYCView.as_view(), name = 'kyc'),
    path('faite-vous-connaitre/denomination', KYCViewDenomination.as_view(), name = 'kyc-denomination'),
    path('faite-vous-connaitre/lieu-de-culte', KYCViewPlace.as_view(), name = 'kyc-place'),
    path('faite-vous-connaitre/service', KYCViewService.as_view(), name = 'kyc-service'),
]

# AJAX PATTERNS
urlpatterns += [
    re_path(r'^ajax/location-search$', location_search, name = 'location-search'),
    re_path(r'^ajax/place-search$', place_search, name = 'place-search'),
    re_path(r'^ajax/get-location$', get_location, name = 'get-location'),
    re_path(r'^ajax/get-next-celebration$', get_next_celebration, name = 'get-next'),
    re_path(r'^ajax/add-activity-request$', ActivityRequestView.as_view(), name = 'add-activity-request'),
    re_path(r'^ajax/add-contact-request$', ContactRequestView.as_view(), name = 'add-contact-request'),
    re_path(r'^ajax/add-receive-request$', ReceiveRequestCreateView.as_view(), name = 'add-receive-request'),
    re_path(r'^ajax/get-retirement-travel$', get_retirement_travel, name = 'get-retirement-travel'),
]

# FRAMES
urlpatterns += [
    re_path(r'^frame/(?P<request_type>\w+)$', open_frame, name = 'open-frame'),
]

# MAIN ROUTES
urlpatterns += [
    path('<slug:group>', DenominationListView.as_view(), name = 'group'),
    path('<slug:group>/necrologie', NecrologyListView.as_view(), name = 'necrology-list-group'),
    # path('<slug:group>/articles', ArticleListGroupView.as_view(), name = 'articles_group'),
    # path('<slug:group>/announces', views.AnnounceListGroupView.as_view(), name = 'announces_group'),
    # path('<slug:group>/calendar-view', CalendarPartialView.as_view(), name = 'calendar_group_view'),
    path('<slug:group>/', include([
        path('<slug:denomination>', DenominationHomeView.as_view(), name = 'denomination'),
        # NEWS
        path('<slug:denomination>/articles', ArticleListView.as_view(), name = 'article-list'),
        path('<slug:denomination>/article/<slug:slug>', ArticleDetailView.as_view(), name = 'article'),
        path('<slug:denomination>/annonces', AnnounceListView.as_view(), name = 'announce-list'),
        path('<slug:denomination>/annonce/<slug:slug>', AnnounceDetailView.as_view(), name = 'announce'),

        # FAITH
        path('<slug:denomination>/foi', DenominationFaithListView.as_view(), name = 'faith-list'),
        path('<slug:denomination>/foi/<slug:slug>', DenominationFaithView.as_view(), name = 'faith'),

        # DIRECTORY
        path('<slug:denomination>/je-recherche', DirectoryLookupView.as_view(), name = 'directory-lookup'),
        path('<slug:denomination>/directory-search-full', DirectorySearchFullView.as_view(), name = 'directory-search-full'),
        path('<slug:denomination>/annuaire/search', DirectoryWishSearchView.as_view(), name = 'annuaire-search'),
        path('<slug:denomination>/annuaire/<slug:slug>', PlaceView.as_view(), name = 'place'),
        # path('<slug:denomination>/annuaire/<slug:slug>/annonces', PlaceView.as_view(), name = 'place-announces'),
        path('<slug:denomination>/annuaire/<slug:place>/annonces/<slug:announce>', PlaceAnnounceDetailView.as_view(), name = 'place-announce'),
        path('<slug:denomination>/annuaire/<slug:place>/communauté/<slug:community>', PlaceCommunityDetailView.as_view(), name = 'place-community'),
        path('<slug:denomination>/annuaire/<slug:place>/remonter-une-erreur', ContactRequestView.as_view(), name = 'error-report'),
        # FORM ACTIVITY DIRECT LINK
        path('<slug:denomination>/annuaire/<slug:slug>/priere/<int:pk>', PlaceView.as_view(), name = 'prayer'),
        path('<slug:denomination>/evenements/<slug:slug>', EventView.as_view(), name = 'event'),
        path('<slug:denomination>/services/<slug:slug>', ServiceView.as_view(), name = 'service'),

        # TOOLS
        path('<slug:denomination>/faire-une-demande', ActivityRequestView.as_view(), name = 'activity-request'),
        path('<slug:denomination>/faire-une-demande/p/<slug:place>', ActivityRequestView.as_view(),
             name = 'activity-request-from-place'),
        path('<slug:denomination>/faire-une-demande/n/<slug:necrology>', ActivityRequestView.as_view(),
             name = 'activity-request-from-necrology'),
        path('<slug:denomination>/contacter', ContactRequestView.as_view(), name = 'contact-request'),

        path('<slug:denomination>/demandes', ReceiveRequestListView.as_view(), name = 'receive-list'),
        path('<slug:denomination>/demandes/<int:pk>', ReceiveRequestDetailView.as_view(), name = 'receive'),
        path('<slug:denomination>/solliciter-une-aide', ReceiveRequestCreateView.as_view(), name = 'receive-create'),
        path('<slug:denomination>/demandes/<int:pk>/donner', ReceiveRequestDonationView.as_view(), name = 'receive-donate'),

        # RETIREMENT
        path('<slug:denomination>/pelerinages-retraites', RetirementPlaceListView.as_view(), name = 'retirement-place-list'),
        path('<slug:denomination>/retirement-search', RetirementSearchView.as_view(), name = 'retirement-search'),
        path('<slug:denomination>/pelerinages-retraites/recherche', RetirementTravelSearchView.as_view(), name = 'retirement-travel-search'),
        path('<slug:denomination>/pelerinages-retraites/<slug:slug>', RetirementPlaceDetailView.as_view(), name = 'retirement-place'),

        # NECROLOGY
        path('<slug:denomination>/necrologie', NecrologyListView.as_view(), name = 'necrology-list'),
        path('<slug:denomination>/necrologie/search', NecrologyListView.as_view(), name = 'necrology-search'),
        path('<slug:denomination>/necrologie/<slug:slug>', NecrologyDetailView.as_view(), name = 'necrology'),

        # TESTIMONY
        path('<slug:denomination>/temoignages', TestimonyListView.as_view(), name = 'testimony-list'),
        path('<slug:denomination>/testimony/<slug:slug>', TestimonyDetailView.as_view(), name = 'testimony'),

        # MEDIA
        path('<slug:denomination>/ebook', EbookListView.as_view(), name = 'ebook-ist'),
        # path('<slug:denomination>/ebook/<slug:slug>', EbookDetailView.as_view(), name = 'ebook'),
        path('<slug:denomination>/mediatheque', GalleryListView.as_view(), name = 'media-list'),
        path('<slug:denomination>/mediatheque/<slug:type>', GalleryView.as_view(), name = 'media-type'),
        path('<slug:denomination>/mediatheque/<slug:type>/<int:pk>', GalleryDetailView.as_view(), name = 'media'),
    ])),
]

prions/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.utils.translation import ugettext_lazy
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

from prions.settings import cfg

admin.site.site_title = ugettext_lazy('{}'.format(cfg.get('PROJECT', 'APP_DESCRIPTION')))
admin.site.site_header = ugettext_lazy('{}'.format(cfg.get('PROJECT', 'APP_DESCRIPTION')))

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url = '/static/core/icons/favicon.ico')),
    # path('api/', include('backend.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace = 'core')),
    path('administrator/', include('apps.administrator.urls', namespace = 'administrator')),
    # re_path('api/(?P<version>(v1|v2))/', include('apps.api.urls', namespace = 'api')),
    # path('api-auth/', include('rest_framework.urls', namespace = 'rest_framework')),
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# Other plugins urls
urlpatterns += [
    re_path(r'^captcha/', include('captcha.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

# If you already have a js_info_dict dictionary, just add
# 'recurrence' to the existing 'packages' tuple.
"""js_info_dict = {
    'packages': ('recurrence',),
}"""

# jsi18n can be anything you like here
"""urlpatterns += [
    re_path(r'^jsi18n/$', JavaScriptCatalog.as_view(), js_info_dict),
]"""

urlpatterns += [path('jsi18n.js', JavaScriptCatalog.as_view(packages = ['recurrence']), name = 'jsi18n'), ]

# For Ads
# urlpatterns += re_path(r'^ads/', include('ads.urls')),

if settings.DEBUG is True:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

apps/administrator/views/announce.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, ListView, UpdateView

from apps.administrator.forms import PlaceAnnounceForm
from apps.religion.models import Group, Denomination, Place, PlaceAnnounce


class AnnounceListView(LoginRequiredMixin, ListView):
    model = PlaceAnnounce
    template_name = 'administrator/announce/announce_list.html'
    login_url = '/administrator/login/'

    def get_queryset(self):
        place = get_object_or_404(Place, slug = 'sainte-cecile')
        return PlaceAnnounce.objects.filter(place = place)

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'announce'
        context['page_name'] = 'announce_list'
        context['page_title'] = 'Liste des annonces'

        return context


class AnnounceCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = PlaceAnnounce
    template_name = 'administrator/announce/announce_create.html'
    form_class = PlaceAnnounceForm
    login_url = '/administrator/login/'
    success_url = '/administrator/announces/'
    success_message = "Annonce ajoutée avec succès"
    place = None

    def get_initial(self):
        initial = super().get_initial()
        self.place = get_object_or_404(Place, slug = 'sainte-cecile')
        initial['place'] = self.place
        initial['denomination'] = get_object_or_404(Denomination, slug = self.place.denomination.slug)
        initial['group'] = get_object_or_404(Group, slug = self.place.denomination.group.slug)
        return initial

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'announce'
        context['page_name'] = 'announce_create'
        context['page_title'] = 'Créer une annonce'

        return context


class AnnounceUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = PlaceAnnounce
    template_name = 'administrator/announce/announce_update.html'
    form_class = PlaceAnnounceForm
    login_url = '/administrator/login/'
    success_url = '/administrator/announces/'
    success_message = "Annonce mise à jour avec succès"

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'announce'
        context['page_name'] = 'announce_update'
        context['page_title'] = 'Mettre à jour une annonce'

        return context

apps/administrator/views/post.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, ListView, UpdateView

from apps.administrator.forms import PlaceCategoryForm, PlaceTagForm
from apps.religion.models import Group, Denomination, Place, PlaceCategory, PlaceTag


class CategoryListView(LoginRequiredMixin, ListView):
    model = PlaceCategory
    template_name = 'administrator/post/category_list.html'
    login_url = '/administrator/login/'

    def get_queryset(self):
        place = get_object_or_404(Place, slug = 'sainte-cecile')
        return PlaceCategory.objects.filter(place = place)

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'category'
        context['page_name'] = 'category_list'
        context['page_title'] = 'Liste des catégories'

        return context


class CategoryCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = PlaceCategory
    template_name = 'administrator/post/category_create.html'
    form_class = PlaceCategoryForm
    login_url = '/administrator/login/'
    success_url = '/administrator/categories/'
    success_message = 'Catégorie ajoutée avec succès'
    place = None

    def get_initial(self):
        initial = super().get_initial()
        self.place = get_object_or_404(Place, slug = 'sainte-cecile')
        initial['place'] = self.place
        initial['denomination'] = get_object_or_404(Denomination, slug = self.place.denomination.slug)
        initial['group'] = get_object_or_404(Group, slug = self.place.denomination.group.slug)
        return initial

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'category'
        context['page_name'] = 'category_create'
        context['page_title'] = 'Créer une catégorie'

        return context


class CategoryUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = PlaceCategory
    template_name = 'administrator/post/category_update.html'
    form_class = PlaceCategoryForm
    login_url = '/administrator/login/'
    success_url = '/administrator/categories/'
    success_message = 'Catégorie mise à jour avec succès'

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'category'
        context['page_name'] = 'category_update'
        context['page_title'] = 'Mettre à jour une catégorie'

        return context


class TagListView(LoginRequiredMixin, ListView):
    model = PlaceTag
    template_name = 'administrator/post/tag_list.html'
    login_url = '/administrator/login/'

    def get_queryset(self):
        place = get_object_or_404(Place, slug = 'sainte-cecile')
        return PlaceTag.objects.filter(place = place)

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'tag'
        context['page_name'] = 'tag_list'
        context['page_title'] = 'Liste des tags'

        return context


class TagCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = PlaceTag
    template_name = 'administrator/post/tag_create.html'
    form_class = PlaceTagForm
    login_url = '/administrator/login/'
    success_url = '/administrator/tags/'
    success_message = 'Tag ajouté avec succès'
    place = None

    def get_initial(self):
        initial = super().get_initial()
        self.place = get_object_or_404(Place, slug = 'sainte-cecile')
        initial['place'] = self.place
        initial['denomination'] = get_object_or_404(Denomination, slug = self.place.denomination.slug)
        initial['group'] = get_object_or_404(Group, slug = self.place.denomination.group.slug)
        return initial

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'tag'
        context['page_name'] = 'tag_create'
        context['page_title'] = 'Créer un tag'

        return context


class TagUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = PlaceTag
    template_name = 'administrator/post/tag_update.html'
    form_class = PlaceTagForm
    login_url = '/administrator/login/'
    success_url = '/administrator/tags/'
    success_message = 'Tag mis à jour avec succès'

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'tag'
        context['page_name'] = 'tag_update'
        context['page_title'] = 'Mettre à jour un tag'

        return context

apps/core/templates/core/denomination/posts/announce.html
{% extends 'core/layouts/denomination.html' %}
{% load static thumbnail social_share %}
{% block title %}{{ page_title|default:"Bienvenue sur Prions.ci" }}{% endblock %}
{% block content %}
    <section class="medium-gap single-post">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="single-posts">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="single-post">
                                    <div class="post-image">
                                        <div class="meta-category">
                                            <span>{{ announce.category.name }}</span>
                                        </div>
                                        {% thumbnail announce.image "730x398" as im %}
                                            <img src="{{ im.url }}" width="{{ im.width }}"
                                                 height="{{ im.height }}" alt="{{ announce.title }}">
                                        {% empty %}
                                            <img src="https://placehold.jp/cccccc/ffffff/730x398.png?text=Aucune%20Image%20trouv%C3%A9e"
                                                 alt="{{ announce.title }}">
                                        {% endthumbnail %}
                                    </div>
                                    <div class="down-content">
                                        <h4>{{ announce.title }}</h4>
                                        <ul class="post-info">
                                            <li><i class="fa fa-calendar"></i> {{ announce.published_on|date:"j F Y H:i" }}</li>
                                            <li><i class="fa fa-eye"></i> 0</li>
                                        </ul>
                                        <div class="mt-4 mb-4 content-safe">{{ announce.content|safe }}</div>
                                        <div class="row">
                                            <div class="col-lg-7 col-md-6 offset-lg-5 offset-md-6">
                                                <!-- Post Single - Share -->
                                                <div class="si-share noborder clearfix">
                                                    <span>Partagez cette annonce :</span>
                                                    <div>
                                                        {% post_to_facebook request.build_absolute_uri '<i class="icon-facebook"></i>' %}
                                                        {% post_to_twitter '<text_to_post>' request.build_absolute_uri '<i class="icon-twitter"></i>' %}
                                                        {% post_to_whatsapp request.build_absolute_uri '<i class="icon-whatsapp"></i>' %}
                                                        {% post_to_telegram '<text_to_post>' request.build_absolute_uri '<i class="icon-telegram"></i>' %}
                                                        {% post_to_linkedin '#' %}
                                                        {% post_to_gplus request.build_absolute_uri '<i class="icon-gplus"></i>' %}
                                                        {% send_email '<subject>' '<text_to_post>' request.build_absolute_uri '<i class="icon-email3"></i>' %}
                                                    </div>
                                                </div>
                                                <!-- Post Single - Share End -->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <ul class="post-nav">
                                    {% if previous_article %}
                                        <li><a href="{{ previous_announce.get_absolute_url }}">&lArr; Pr&eacute;c&eacute;dent</a></li>
                                    {% endif %}
                                    {% if next_article %}
                                        <li><a href="{{ next_announce.get_absolute_url }}">Suivant &rArr;</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    {% include 'core/denomination/partials/sidebar.html' %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

apps/core/templates/core/denomination/posts/necrology_list.html
{% extends 'core/layouts/denomination.html' %}
{% load utils %}
{% load static thumbnail crispy_forms_tags %}
{% block title %}{{ page_title|default:"Bienvenue sur Prions.ci" }}{% endblock %}
{% block content %}
    <section class="large-gap standard-home recent-home">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="standard-posts">
                        <div class="row mb-4">
                            <div class="col-12">
                                <form action="{% url 'core:necrology-search' group.slug denomination.slug %}" method="POST"
                                      id="necrology-search-form">
                                    {% csrf_token %}
                                    <div class="input-group">
                                        <input type="text"
                                               id="necrology-search"
                                               name="necrology_search"
                                               class="form-control necrology-search"
                                               placeholder="Rechercher un avis de décès"
                                               minlength="3"
                                               autocomplete="off">
                                        <div class="input-group-append">
                                            <button class="btn button-color"
                                                    type="submit"
                                                    data-toggle="tooltip"
                                                    title="Chercher">
                                                <i class="fa fa-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-12">
                                {% if is_searched %}
                                    {% if necrology_list.count == 0 %}
                                        Aucun r&eacute;sultat <br>
                                        <a href="{% url 'core:necrology-list' group.slug denomination.slug %}"
                                           class="button button-reveal button-small tright m-0 mt-2">
                                            <i class="fa fa-arrow-right"></i><span>Voir tout</span></a>
                                    {% else %}
                                        {% to_plural necrology_list.count "résultat" "résultats" %}
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            {% for necrology in necrology_list %}
                                <div class="col-lg-6">
                                    <div class="standard-post recent-post">
                                        <div class="post-image">
                                            <a href="{% url 'core:necrology' group.slug denomination.slug necrology.slug %}">
                                                {% thumbnail necrology.image "350x288" crop="80% top" as im %}
                                                    <img src="{{ im.url }}" width="{{ im.width }}"
                                                         height="{{ im.height }}" alt="{{ necrology.title }}">
                                                {% empty %}
                                                    <img src="https://placehold.jp/cccccc/ffffff/350x288.png?text=Aucune%20Image%20trouv%C3%A9e"
                                                         alt="{{ necrology.title }}">
                                                {% endthumbnail %}
                                            </a>
                                        </div>
                                        <div class="down-content">
                                            <a href="{% url 'core:necrology' group.slug denomination.slug necrology.slug %}">
                                                <h4>{{ necrology.title }}</h4>
                                            </a>
                                            <ul class="post-info">
                                                <li>D&eacute;c&egrave;s survenu le {{ necrology.date }}</li>
                                            </ul>
                                            <p>{{ necrology.excerpt|truncatechars:150 }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    {% include 'core/denomination/partials/sidebar.html' %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

apps/core/templates/core/denomination/posts/testimony_list.html
{% extends 'core/layouts/denomination.html' %}
{% load static thumbnail crispy_forms_tags %}
{% block title %}{{ page_title|default:"Bienvenue sur Prions.ci" }}{% endblock %}
{% block content %}
    <section class="large-gap standard-home">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="standard-posts">
                        <div class="row">
                            {% for testimony in testimony_list %}
                                <div class="col-lg-12">
                                    <div class="standard-post">
                                        <div class="down-content">
                                            <a href="{% url 'core:testimony' group.slug denomination.slug testimony.slug %}">
                                                <h4>{{ testimony.title }}</h4>
                                            </a>
                                            <ul class="post-info">
                                                <li><i class="fa fa-calendar"></i> {{ testimony.created_at|date:"j F Y" }}</li>
                                                <li><i class="fa fa-eye"></i> 0</li>
                                            </ul>
                                            <p>{{ testimony.excerpt|safe|truncatechars:150 }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% empty %}
                                <div class="col-12">
                                    Aucun t&eacute;moignage re&ccedil;u pour le moment
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    {% include 'core/denomination/partials/sidebar.html' %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}