apps/core/urls.py
from django.urls import path, include, re_path

from apps.core.views import *

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name = 'index'),
    path('qui-sommes-nous', AboutUsView.as_view(), name = 'about-us'),
    path('faite-vous-connaitre', KYCView.as_view(), name = 'kyc'),
    path('faite-vous-connaitre/denomination', KYCViewDenomination.as_view(), name = 'kyc-denomination'),
    path('faite-vous-connaitre/lieu-de-culte', KYCViewPlace.as_view(), name = 'kyc-place'),
    path('faite-vous-connaitre/service', KYCViewService.as_view(), name = 'kyc-service'),
]

# AJAX PATTERNS
urlpatterns += [
    re_path(r'^ajax/location-search$', location_search, name = 'location-search'),
    re_path(r'^ajax/place-search$', place_search, name = 'place-search'),
    re_path(r'^ajax/get-location$', get_location, name = 'get-location'),
    re_path(r'^ajax/get-next-celebration$', get_next_celebration, name = 'get-next'),
    re_path(r'^ajax/add-activity-request$', ActivityRequestView.as_view(), name = 'add-activity-request'),
    re_path(r'^ajax/add-contact-request$', ContactRequestView.as_view(), name = 'add-contact-request'),
    re_path(r'^ajax/add-receive-request$', ReceiveRequestCreateView.as_view(), name = 'add-receive-request'),
    re_path(r'^ajax/get-retirement-travel$', get_retirement_travel, name = 'get-retirement-travel'),
]

# FRAMES
urlpatterns += [
    re_path(r'^frame/(?P<request_type>\w+)$', open_frame, name = 'open-frame'),
]

# MAIN ROUTES
urlpatterns += [
    path('<slug:group>', DenominationListView.as_view(), name = 'group'),
    path('<slug:group>/necrologie', NecrologyListView.as_view(), name = 'necrology-list-group'),
    # path('<slug:group>/articles', ArticleListGroupView.as_view(), name = 'articles_group'),
    # path('<slug:group>/announces', views.AnnounceListGroupView.as_view(), name = 'announces_group'),
    # path('<slug:group>/calendar-view', CalendarPartialView.as_view(), name = 'calendar_group_view'),
    path('<slug:group>/', include([
        path('<slug:denomination>', DenominationHomeView.as_view(), name = 'denomination'),
        # NEWS
        path('<slug:denomination>/articles', ArticleListView.as_view(), name = 'article-list'),
        path('<slug:denomination>/article/<slug:slug>', ArticleDetailView.as_view(), name = 'article'),
        path('<slug:denomination>/annonces', AnnounceListView.as_view(), name = 'announce-list'),
        path('<slug:denomination>/annonce/<slug:slug>', AnnounceDetailView.as_view(), name = 'announce'),

        # FAITH
        path('<slug:denomination>/foi', DenominationFaithListView.as_view(), name = 'faith-list'),
        path('<slug:denomination>/foi/<slug:slug>', DenominationFaithView.as_view(), name = 'faith'),

        # DIRECTORY
        path('<slug:denomination>/je-recherche', DirectoryLookupView.as_view(), name = 'directory-lookup'),
        path('<slug:denomination>/directory-search-full', DirectorySearchFullView.as_view(), name = 'directory-search-full'),
        path('<slug:denomination>/annuaire/search', DirectoryWishSearchView.as_view(), name = 'annuaire-search'),
        path('<slug:denomination>/annuaire/<slug:slug>', PlaceView.as_view(), name = 'place'),
        # path('<slug:denomination>/annuaire/<slug:slug>/annonces', PlaceView.as_view(), name = 'place-announces'),
        path('<slug:denomination>/annuaire/<slug:place>/annonces/<slug:announce>', PlaceAnnounceDetailView.as_view(), name = 'place-announce'),
        path('<slug:denomination>/annuaire/<slug:place>/communauté/<slug:community>', PlaceCommunityDetailView.as_view(), name = 'place-community'),
        path('<slug:denomination>/annuaire/<slug:place>/remonter-une-erreur', ContactRequestView.as_view(), name = 'error-report'),
        # FORM ACTIVITY DIRECT LINK
        path('<slug:denomination>/annuaire/<slug:slug>/priere/<int:pk>', PlaceView.as_view(), name = 'prayer'),
        path('<slug:denomination>/evenements/<slug:slug>', EventView.as_view(), name = 'event'),
        path('<slug:denomination>/services/<slug:slug>', ServiceView.as_view(), name = 'service'),

        # TOOLS
        path('<slug:denomination>/faire-une-demande', ActivityRequestView.as_view(), name = 'activity-request'),
        path('<slug:denomination>/faire-une-demande/p/<slug:place>', ActivityRequestView.as_view(),
             name = 'activity-request-from-place'),
        path('<slug:denomination>/faire-une-demande/n/<slug:necrology>', ActivityRequestView.as_view(),
             name = 'activity-request-from-necrology'),
        path('<slug:denomination>/contacter', ContactRequestView.as_view(), name = 'contact-request'),

        path('<slug:denomination>/demandes', ReceiveRequestListView.as_view(), name = 'receive-list'),
        path('<slug:denomination>/demandes/<int:pk>', ReceiveRequestDetailView.as_view(), name = 'receive'),
        path('<slug:denomination>/solliciter-une-aide', ReceiveRequestCreateView.as_view(), name = 'receive-create'),
        path('<slug:denomination>/demandes/<int:pk>/donner', ReceiveRequestDonationView.as_view(), name = 'receive-donate'),

        # RETIREMENT
        path('<slug:denomination>/pelerinages-retraites', RetirementPlaceListView.as_view(), name = 'retirement-place-list'),
        path('<slug:denomination>/retirement-search', RetirementSearchView.as_view(), name = 'retirement-search'),
        path('<slug:denomination>/pelerinages-retraites/recherche', RetirementTravelSearchView.as_view(), name = 'retirement-travel-search'),
        path('<slug:denomination>/pelerinages-retraites/<slug:slug>', RetirementPlaceDetailView.as_view(), name = 'retirement-place'),

        # NECROLOGY
        path('<slug:denomination>/necrologie', NecrologyListView.as_view(), name = 'necrology-list'),
        path('<slug:denomination>/necrologie/search', NecrologyListView.as_view(), name = 'necrology-search'),
        path('<slug:denomination>/necrologie/<slug:slug>', NecrologyDetailView.as_view(), name = 'necrology'),

        # TESTIMONY
        path('<slug:denomination>/temoignages', TestimonyListView.as_view(), name = 'testimony-list'),
        path('<slug:denomination>/testimony/<slug:slug>', TestimonyDetailView.as_view(), name = 'testimony'),

        # MEDIA
        path('<slug:denomination>/ebook', EbookListView.as_view(), name = 'ebook-ist'),
        # path('<slug:denomination>/ebook/<slug:slug>', EbookDetailView.as_view(), name = 'ebook'),
        path('<slug:denomination>/mediatheque', GalleryListView.as_view(), name = 'media-list'),
        path('<slug:denomination>/mediatheque/<slug:type>', GalleryView.as_view(), name = 'media-type'),
        path('<slug:denomination>/mediatheque/<slug:type>/<int:pk>', GalleryDetailView.as_view(), name = 'media'),
    ])),
]

prions/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.utils.translation import ugettext_lazy
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

from prions.settings import cfg

admin.site.site_title = ugettext_lazy('{}'.format(cfg.get('PROJECT', 'APP_DESCRIPTION')))
admin.site.site_header = ugettext_lazy('{}'.format(cfg.get('PROJECT', 'APP_DESCRIPTION')))

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url = '/static/core/icons/favicon.ico')),
    # path('api/', include('backend.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace = 'core')),
    path('administrator/', include('apps.administrator.urls', namespace = 'administrator')),
    # re_path('api/(?P<version>(v1|v2))/', include('apps.api.urls', namespace = 'api')),
    # path('api-auth/', include('rest_framework.urls', namespace = 'rest_framework')),
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# Other plugins urls
urlpatterns += [
    re_path(r'^captcha/', include('captcha.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

# If you already have a js_info_dict dictionary, just add
# 'recurrence' to the existing 'packages' tuple.
"""js_info_dict = {
    'packages': ('recurrence',),
}"""

# jsi18n can be anything you like here
"""urlpatterns += [
    re_path(r'^jsi18n/$', JavaScriptCatalog.as_view(), js_info_dict),
]"""

urlpatterns += [path('jsi18n.js', JavaScriptCatalog.as_view(packages = ['recurrence']), name = 'jsi18n'), ]

# For Ads
# urlpatterns += re_path(r'^ads/', include('ads.urls')),

if settings.DEBUG is True:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

apps/core/views/ajax.py
import json
from datetime import datetime
from itertools import chain

from django.contrib.sites.models import Site
from django.core import signing
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt

from apps.location.models import City, Town, Borough
from apps.religion.models import Place, Group, Denomination, PlaceActivity
from apps.retirement.models import RetirementTravelInstance
from lib.config import django_logger
from lib.middleware import api_call, str_to_json, get_geo_loc, get_occurrences, nearest_date, get_class_instance, get_activity, JSONEncoder
from lib.resources import confs


def location_search(request):
    get_data = request.GET
    location = get_data.get('location', None)

    status = False
    results = []

    cities_list = City.objects.filter(name__icontains = location).values()
    city = [dict(x, type = 'city') for x in cities_list]

    towns_list = Town.objects.filter(name__icontains = location).values()
    town = [dict(x, type = 'town') for x in towns_list]

    boroughs_list = Borough.objects.filter(name__icontains = location).values()
    borough = [dict(x, type = 'borough') for x in boroughs_list]

    values = sorted(chain(city, town, borough), key = lambda instance: instance['name'])

    if values:
        status = True
        results = values

    data = {
        'status': status,
        'results': results,
    }

    return JsonResponse(data, safe = False)


def place_search(request):
    get_data = request.GET
    place_name = get_data.get('place_name', '')
    place_type = get_data.get('place_type', '')
    denomination = get_data.get('denomination', '')

    status = False
    results = []

    place = Place.objects.posted_by_denomination(denomination)
    if len(place_type) > 0:
        place = place.filter(place_type = place_type)
    place = place.filter(name__icontains = place_name)

    if place:
        status = True
        results = list(place.values())

    data = {
        'status': status,
        'results': results,
    }

    return JsonResponse(data, safe = False)


@csrf_exempt
def get_location(request):
    latitude = request.POST.get('latitude', None)
    longitude = request.POST.get('longitude', None)

    if latitude and longitude:
        geo_api = confs.get('api')['GEO_API']

        url = geo_api['url'].replace('{latitude}', latitude).replace('{longitude}', longitude)
        place = api_call(url = url, method = geo_api['method'], timeout = 5)

        if not hasattr(place, 'status_code'):
            out_msg = place["message"]
            django_logger.error("GEO API NOT REACHABLE !!! => {}".format(out_msg))

            return JsonResponse(None, safe = False)
        else:
            r = place.text
            return JsonResponse(json.loads(r))


def get_retirement_travel(request):
    get_data = request.GET
    instance_id = get_data.get('instance', '')
    group_id = get_data.get('group', '')
    denomination_id = get_data.get('denomination', '')

    group = get_class_instance(Group, pk = group_id)
    denomination = get_class_instance(Denomination, pk = denomination_id)

    status = False

    instance = get_class_instance(RetirementTravelInstance, pk = instance_id)
    template = ''

    if instance:
        status = True
        # template = TemplateResponse(request, 'core/denomination/partials/modals/retirement_travel_instance.html', context = instance)
        context = {
            'request': request,
            'group': group,
            'denomination': denomination,
            'instance': instance
        }
        template = render_to_string('core/denomination/partials/modals/retirement_travel_instance.html', context)

    data = {
        'status': status,
        'travel_title': '{} ({})'.format(instance.retirement_travel.title, instance.departure_date.year),
        'template': template,
    }

    return JsonResponse(data, safe = False)


@csrf_exempt
def get_next_celebration(request):
    post = request.POST
    group = post.get('group', None)
    denomination = post.get('denomination', None)
    geo_loc = str_to_json(post.get('address', ""))

    from apps.religion.models import PlaceActivity
    place_activities = PlaceActivity.objects.filter(place__denomination = denomination, activity__activity_type__codename = "messe")

    search_result = get_geo_loc(PlaceActivity, geo_loc, place_activities, by = "address", place = True)

    occ = [get_occurrences(x.id, 'next') for x in search_result if get_occurrences(x.id, 'next') and x.recurrences is not None]

    next_occ = nearest_date(occ, datetime.today().date())
    template = ''

    if next_occ is None:
        status = False
    else:
        status = True
        domain = Site.objects.get_current().domain
        pa = next_occ.get('place_activity', {})
        date = next_occ.get('date', None)
        pa_params = {'frame': True, 'type': 'activity', 'id': pa.activity.pk, 'date': date.strftime('%d-%m-%Y')}
        encoded_params = signing.dumps(pa_params)
        # next_occ['url'] = url_with_querystring(domain, encoded_params)
        next_occ['url'] = "{}?r={}".format(domain, encoded_params)
        next_occ['request'] = request
        template = render_to_string('core/denomination/partials/modals/next_celebration.html', next_occ)

    data = {
        'status': status,
        'template': template,
    }

    return JsonResponse(data)


def open_frame(request, params):
    if bool(params) is True:
        request_type = params.get('type')
        pa_id = params.get('id')
        date = params.get('date')
        if request_type == 'activity':
            place_activity = get_class_instance(PlaceActivity, pa_id)
            activity_date = date
            occ = get_activity(place_activity, activity_date)
            next_occ = nearest_date(occ, datetime.today().date())
            next_occ['request'] = request
            next_occ['frame'] = True

            template = ''

            if next_occ is None:
                status = False
            else:
                status = True
                template = render_to_string('core/denomination/partials/modals/next_celebration.html', next_occ)

            data = {
                'status': status,
                'template': template,
            }

            return json.dumps(data)

        print("get_data => {}".format(get_data))
        instance_id = get_data.get('instance', '')
        group_id = get_data.get('group', '')
        denomination_id = get_data.get('denomination', '')
        frame = get_data.get('open_frame', '')
        print("frame => {}".format(frame))
        return

        group = get_class_instance(Group, pk = group_id)
        denomination = get_class_instance(Denomination, pk = denomination_id)

        status = False

        instance = get_class_instance(RetirementTravelInstance, pk = instance_id)
        template = ''

        if instance:
            status = True
            # template = TemplateResponse(request, 'core/denomination/partials/modals/retirement_travel_instance.html', context = instance)
            context = {
                'request': request,
                'group': group,
                'denomination': denomination,
                'instance': instance
            }
            template = render_to_string('core/denomination/partials/modals/retirement_travel_instance.html', context)

        data = {
            'status': status,
            'travel_title': '{} ({})'.format(instance.retirement_travel.title, instance.departure_date.year),
            'template': template,
        }

        return JsonResponse(data, safe = False)

apps/core/templates/core/denomination/partials/page-title.html
{% load utils sitetree %}
<section class="large-gap call-to-action">
    <div class="row">
        <div class="col-lg-12">
            <div class="main-content" style="background-image:url({{ group.background.url }}); background-position-y: 30%;
                    background-size: cover;">
                <div class="container">
                    <div class="row">
                        <div class="row col-lg-8">
                            <div class="left-content">
                                <h1 class="h2 nott color-white">{{ page_title|default:"Bienvenue sur le portail Chr&eacute;tien de Prions.ci"|truncatewords:10 }}</h1>
                            </div>
                        </div>
                        <div class="row col-lg-8">
                            {% sitetree_breadcrumbs from "menu_"|add:denomination.slug template "sitetree/breadcrumbs.html" %}
                            {% comment %}<ol class="breadcrumb">
                                    <li class="breadcrumb-item">
                                        <a href="{% url 'core:denomination' group.slug denomination.slug %}">Accueil</a>
                                    </li>
                                    {% if page_name|in_list:'post,posts_search,categories' %}
                                        <li class="breadcrumb-item">
                                            <a href="{% url 'core:article-list' group.slug denomination.slug %}">News</a>
                                        </li>
                                    {% endif %}
                                    {% if page_name|in_list:'announce,announces_search' %}
                                        <li class="breadcrumb-item">
                                            <a href="{% url 'core:announce-list' group.slug denomination.slug %}">Annonces</a>
                                        </li>
                                    {% endif %}
                                    {% if page_name|in_list:'faith' %}
                                        <li class="breadcrumb-item">
                                            <a href="{% url 'core:foi-list' group.slug denomination.slug %}">Foi {{ denomination.denomination_details.common_name }}</a>
                                        </li>
                                    {% endif %}
                                    {% if page_name|in_list:'place' %}
                                        <li class="breadcrumb-item">
                                            <a href="{% url 'core:directory-lookup' group.slug denomination.slug %}">Je Recherche</a>
                                        </li>
                                    {% endif %}
                                    {% if menu|in_list:'tools' %}
                                        <li class="breadcrumb-item">
                                            <a href="#">Outils</a>
                                        </li>
                                    {% endif %}
                                    {% if page_name|in_list:'media_list,media_type,media' %}
                                        <li class="breadcrumb-item">
                                            <a href="{% url 'core:media-list' group.slug denomination.slug %}">M&eacute;diath&egrave;que</a>
                                        </li>
                                    {% endif %}
                                    {% if page_name|in_list:'receive-list,receive_create,receive_detail' %}
                                        <li class="breadcrumb-item">
                                            <a href="{% url 'core:receive-list' group.slug denomination.slug %}">Donner & Recevoir</a>
                                        </li>
                                    {% endif %}
                                    {% if page_name == 'posts_search' %}
                                        <li class="breadcrumb-item">Rechercher un article</li>
                                    {% else %}
                                        {% if page_name != 'denomination' %}
                                            <li class="breadcrumb-item active">{{ page_title }}</li>
                                        {% endif %}
                                    {% endif %}
                                </ol>{% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

apps/core/templates/core/denomination/partials/sidebar.html
{% load static templates utils %}
<div class="main-sidebar right-sidebar">
    <div class="row">
        <div class="col-lg-12 col-sm-6 col-md-6">
            <div class="ads">
                <a href="/media/ads/celebration-VS.jpg" data-lightbox="image">
                    <img src="{% get_media_prefix %}ads/celebration-VS.jpg" width="350" height="288" alt="{{ picture.title }}">
                </a>
            </div>
        </div>

        {% if page_name == 'retirement' %}
            <div class="col-lg-12 col-sm-6 col-md-6 map bottommargin-sm">
                <div class="fancy-title title-dotted-border title-center">
                    <h4 class="color">Situation G&eacute;ographique</h4>
                </div>
                {{ retirement_place.map | default:"Pas encore disponible" | safe }}
            </div>

            <div class="col-lg-12 col-sm-12 col-md-12 bottommargin-sm">
                <a href="{{ retirement_place.e_shop|default_if_none:"#" }}" target="_blank"
                   class="button button-3d button-amber btn-block noleftmargin norightmargin text-center e-shop-button">
                    E-boutique <br> {{ retirement_place.name }}
                </a>
            </div>
        {% endif %}

        {% if not request.user_agent.is_mobile and page_name == 'necrology' %}
            <div class="col-lg-12 col-sm-12 col-md-12 bottommargin-sm">
                <div class="necrology-div center">
                    <a href="{% url 'core:activity-request-from-necrology' group.slug denomination.slug necrology.slug %}"
                       class="button button-3d button-amber noleftmargin norightmargin text-center necrology">
                        {{ denomination.denomination_details.necrology_activity_request }}
                    </a>
                </div>
            </div>
        {% endif %}

        {% if menu == 'receives' %}
            {% if page_name|in_list:"receive_detail,receive_create" %}
                <div class="col-lg-12 col-sm-6 col-md-6 bottommargin-sm">
                    <div class="receive_div center">
                        <a href="{% url 'core:receive-list' group.slug denomination.slug %}"
                           class="button button-3d button-color btn-block noleftmargin norightmargin">
                            <div>Faire une bonne action</div>
                        </a>
                    </div>
                </div>
            {% endif %}
            {% if page_name|in_list:"receive_list,receive_detail" and not request.user_agent.is_mobile %}
                <div class="col-lg-12 col-sm-6 col-md-6 bottommargin-sm">
                    <div class="receive-div center">
                        <a href="{% url 'core:receive-create' group.slug denomination.slug %}" data-animate="tada"
                           class="button button-3d button-red btn-block noleftmargin norightmargin button-desc receive">
                            <div>SOS</div>
                            <span>Solliciter une aide</span>
                        </a>
                    </div>
                </div>
            {% endif %}
        {% endif %}

        {% if page_name != "lookup" %}
            {% if not request.user_agent.is_mobile %}
                {% if denomination.slug == "islam" %}
                    {% include "core/denomination/partials/widgets/islam_prayer_time.html" %}
                {% else %}
                    {% if page_name != 'necrology' %}
                        <div class="col-lg-12 col-sm-12 col-md-12 bottommargin-sm">
                            <button type="button"
                                    class="button button-3d btn-block noleftmargin norightmargin button-desc next-celebration"
                                    data-group="{{ group.id }}"
                                    data-denomination="{{ denomination.id }}"
                                    data-activity-type="messe"
                                    data-toggle="modal">
                                <div>Prochaine Messe</div>
                                <span>Trouver la messe la plus proche</span>
                            </button>
                        </div>
                    {% endif %}
                {% endif %}
                <div class="col-lg-12 col-sm-6 col-md-6 bottommargin-sm">
                    <div class="i-wish">
                        {% i_wish %}
                    </div>
                </div>
            {% elif request.user_agent.is_mobile and menu|in_list:"receives" %}
                {% if denomination.slug == "islam" %}
                    {% include "core/denomination/partials/widgets/islam_prayer_time.html" %}
                {% else %}
                    {% if page_name != 'necrology' %}
                        <div class="col-lg-12 col-sm-12 col-md-12 bottommargin-sm">
                            <button type="button"
                                    class="button button-3d btn-block noleftmargin norightmargin button-desc next-celebration"
                                    data-group="{{ group.id }}"
                                    data-denomination="{{ denomination.id }}"
                                    data-activity-type="messe"
                                    data-toggle="modal">
                                <div>Prochaine Messe</div>
                                <span>Trouver la messe la plus proche</span>
                            </button>
                        </div>
                    {% endif %}
                {% endif %}
                <div class="col-lg-12 col-sm-6 col-md-6 bottommargin-sm">
                    <div class="i-wish">
                        {% i_wish %}
                    </div>
                </div>
            {% endif %}
        {% endif %}

        {% if page_name == "necrology" %}
            {% necrology %}
        {% endif %}

        {% calendar %}

        {% if menu != "necrology" %}
            {% necrology %}
        {% endif %}
    </div>
</div>